### ISSUE TITLE
Put in checks for update changes

### ISSUE THREAD

**Issue by rmuzzelo** [wtaylor45/374-sticks-game#18]

**Comment by rmuzzelo** [comment]
Have to hard-code for 1 and 2

**Comment by ldawson02** [comment]
For each loop and if statements check whether the expected changes will cause any of the percentages to be out of bounds, and adjusts the changes if so. Does not calculate changes for 1 (only one legal move) and only calculates changes for the two legal moves when 2 sticks are left.
